def fct_Calcul_pt_interm(p_debut,p_fin):

    local p_inter = p_fin

    local poucentage = 0.8
    local inc = 0 
    local vecteur_global = p[0,0,0,0,0,0]
    local vecteur_reduit = p[0,0,0,0,0,0]

    while (inc < 6):
        vecteur_global[inc] = p_fin[inc] - p_debut[inc] 
        vecteur_reduit[inc] = vecteur_global[inc]*poucentage
        p_inter[inc] = p_debut[inc] + vecteur_reduit[inc]
        inc = inc +1 
    end 

    return p_inter
end 
