def fun_demande_g():
     close_popup()
     nb_soud_point_g = fun_demande(1)
     nb_soud_lin_g = fun_demande(2)
     if nb_soud_lin_g > 0:
          vit_lin_g = fun_demande_vit(2)
     end
     nb_soud_arc_g = fun_demande(3)
     if nb_soud_arc_g > 0:
          vit_arc_g = fun_demande_vit(3)
     end
     nb_soud_cer_g = fun_demande(4)
     if nb_soud_arc_g > 0:
          vit_cer_g = fun_demande_vit(4)
     end
end 