def pop_up_exe():
    close_popup()
    popup1 ="popup EXECUTION : Les deux tables sont prêtes à l'éxécution" #"popup Appuyer sur le bouton gauche ou droit pour commencer l'éxécution de la pièce sur la table associée. La gestion des modes configuration et éxécution se fait à l'aide du commutateur réglage."
    socket_open("127.0.0.1",29999,"internal") # open internal socket
    socket_send_line(popup1,"internal")     #Affichage message
    socket_send_byte(10,"internal")
end 