#attente front montant sur add_bp

def fun_front_up(add_bp):                      
bp = get_digital_in(add_bp)
    while bp : 
        bp = get_digital_in(add_bp)    #dans la boucle tant que l'entrée add_bp est a 14
        sync()
        #attente relachement bouton
    end
    sync()
    while not bp :                              #dans la boucle tant que l'entrée add_bp est a 0
        bp = get_digital_in(add_bp)
        sync()
        #attente
    end
    sync()
    return(False) 
end