def pop_up_reg_g():
    close_popup()
    popup3 = "popup PAS_A_PAS : Table gauche programmée"#"popup La table gauche est programmée. Appuyer sur le bouton gauche ou droite pour commencer mode pas a pas et le reglage d'une pièce sur la table associée. La gestion des modes programmation, éxécution et reglage se fait à l'aide des commutateurs superieurs."
    socket_open("127.0.0.1",29999,"internal") # open internal socket
    socket_send_line(popup3,"internal")     #Affichage message
    socket_send_byte(10,"internal")
end 